create table public.reference_images (
  id bigint generated by default as identity primary key,
  category text not null,
  storage_path text not null unique,
  original_name text not null,
  alt_text text not null default '',
  sort_order integer not null default 0,
  is_published boolean not null default true,
  uploaded_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  constraint reference_images_category_check check (
    category = any (array['konyha', 'gardrob', 'eloszoba', 'furdo', 'nappali', 'egyedi'])
  ),
  constraint reference_images_alt_text_length_check check (char_length(alt_text) <= 200),
  constraint reference_images_sort_order_check check (sort_order >= 0)
);

create index reference_images_gallery_idx
  on public.reference_images (category, is_published, sort_order, created_at desc);

alter table public.reference_images enable row level security;

grant select on table public.reference_images to anon;
grant select, insert, update, delete on table public.reference_images to authenticated;
grant usage, select on sequence public.reference_images_id_seq to authenticated;

create policy "published reference images are public"
on public.reference_images
for select
to anon, authenticated
using (is_published);

create policy "admins can read all reference images"
on public.reference_images
for select
to authenticated
using (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

create policy "admins can insert reference images"
on public.reference_images
for insert
to authenticated
with check (
  uploaded_by = (select auth.uid())
  and exists (
    select 1
    from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

create policy "admins can update reference images"
on public.reference_images
for update
to authenticated
using (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

create policy "admins can delete reference images"
on public.reference_images
for delete
to authenticated
using (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'reference-images',
  'reference-images',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']::text[]
);

create policy "admins can list reference image objects"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'reference-images'
  and exists (
    select 1
    from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

create policy "admins can upload reference image objects"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'reference-images'
  and (storage.foldername(name))[1] = any (
    array['konyha', 'gardrob', 'eloszoba', 'furdo', 'nappali', 'egyedi']
  )
  and storage.extension(name) = any (array['jpg', 'jpeg', 'png', 'webp', 'avif'])
  and exists (
    select 1
    from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

create policy "admins can update reference image objects"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'reference-images'
  and exists (
    select 1
    from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
)
with check (
  bucket_id = 'reference-images'
  and (storage.foldername(name))[1] = any (
    array['konyha', 'gardrob', 'eloszoba', 'furdo', 'nappali', 'egyedi']
  )
  and storage.extension(name) = any (array['jpg', 'jpeg', 'png', 'webp', 'avif'])
  and exists (
    select 1
    from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

create policy "admins can delete reference image objects"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'reference-images'
  and exists (
    select 1
    from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);
